/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.zhaw.it.pm3;

import ch.zhaw.it.pm3.model.*;
import ch.zhaw.it.pm3.databaseHandling.DataManager;
import ch.zhaw.it.pm3.databaseHandling.Database;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;

class DatabaseTest {
    private DataManager dataManager;
    private User user1;
    private User user2;

    private Advertisement advertisement1;
    private Advertisement advertisement2;

    private List<User> userList;
    private List<Advertisement> advertisementList;
    private List<Offer> offerList;

    private List<Task> taskList;

    @BeforeEach
    void setup() {
        dataManager = DataManager.getInstance();
        userList = new ArrayList<>();
        advertisementList = new ArrayList<>();
        offerList = new ArrayList<>();
        taskList = new ArrayList<>();

        user1 = new User(createUserInfo1(), dataManager.getNewId(userList, User::getId));
        user2 = new User(createUserInfo2(), dataManager.getNewId(userList, User::getId));

        userList.add(user1);
        userList.add(user2);

        advertisement1 = new Advertisement(createDocumentInfo4Ad1(), dataManager.getNewId(advertisementList, Advertisement::getId), user1.getId());
        advertisement2 = new Advertisement(createDocumentInfo4Ad2(), dataManager.getNewId(advertisementList, Advertisement::getId), user2.getId());

        advertisementList.add(advertisement1);
        advertisementList.add(advertisement2);
    }

    private UserInfo createUserInfo1() {
        UserInfo userInfo1 = new UserInfo();
        userInfo1.firstname = "Bruce";
        userInfo1.surname = "Lee";
        userInfo1.mailAddress = "bruce.lee@gmail.com";
        userInfo1.password = "Passwort123!";
        userInfo1.city = "St. Gallen";
        userInfo1.street = "Technikumsstrasse";
        userInfo1.postalCode = 9000;
        userInfo1.companyName = null;
        userInfo1.skill = null;
        userInfo1.lengthExperience = null;
        return userInfo1;
    }

    private UserInfo createUserInfo2() {
        UserInfo userInfo2 = new UserInfo();
        userInfo2.firstname = "Jean-Claude";
        userInfo2.surname = "Van Damme";
        userInfo2.mailAddress = "jean-claude.vandamme@gmail.com";
        userInfo2.password = "JeanClaude123#";
        userInfo2.city = "Winterthur";
        userInfo2.street = "Heinistrasse";
        userInfo2.postalCode = 8003;
        userInfo2.companyName = null;
        userInfo2.skill = null;
        userInfo2.lengthExperience = null;
        return userInfo2;
    }

    private DocumentInfo createDocumentInfo4Ad1() {
        DocumentInfo documentInfo = new DocumentInfo();
        documentInfo.title = "Advertisement 1";
        documentInfo.description = getDescription();

        documentInfo.firstname = "Bruce";
        documentInfo.surname = "Lee";
        documentInfo.street = "Technikumsstrasse";
        documentInfo.postalCode = 9000;
        documentInfo.price = 10000.50;

        return documentInfo;
    }

    private DocumentInfo createDocumentInfo4Ad2() {
        DocumentInfo documentInfo = new DocumentInfo();
        documentInfo.title = "Advertisement 2";
        documentInfo.description = getDescription();

        documentInfo.firstname = "Jean-Claude";
        documentInfo.surname = "Van Damme";
        documentInfo.street = "Heinistrasse";
        documentInfo.postalCode = 8003;
        documentInfo.price = 12345.50;

        return documentInfo;
    }

    private String getDescription() {
        return "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod " +
                "tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam " +
                "et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum" +
                "dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, " +
                "sed diam nonumy eirmod tempor";
    }

    @Test
    void testUsersAreSavedInFile() {
        Database.saveListsToFile(userList, advertisementList, offerList, taskList);
        List<User> readUserList = Database.getUserListFromFile();

        for(int i = 0; i < userList.size(); ++i) {
            assertEquals(userList.get(i).getId(), readUserList.get(i).getId());
        }
    }

    @Test
    void testAdvertisementsAreSavedInFile() {
        Database.saveListsToFile(userList, advertisementList, offerList, taskList);
        List<Advertisement> readAdvertisements = Database.getAdvertisementListFromFile();

        assertEquals(advertisementList.size(), readAdvertisements.size());

        for (int i = 0; i < advertisementList.size(); ++i) {
            assertEquals(advertisementList.get(i).getId(), readAdvertisements.get(i).getId());
        }
    }

    @Test
    void testRemoveAdvertisement() {
        advertisementList.remove(0);
        Database.saveListsToFile(userList, advertisementList, offerList, taskList);
        List<Advertisement> readAdvertisementList = Database.getAdvertisementListFromFile();

        assertEquals(readAdvertisementList.size(), advertisementList.size());
    }
}
