apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app
  labels:
    app: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit
        image: us-central1-docker.pkg.dev/mlops-project-421308/mlops-model/streamlit-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
        env:
        - name: PORT
          value: "8501"
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8501
  selector:
    app: streamlit
