/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.zhaw.it.pm3.ui;

import ch.zhaw.it.pm3.Config;
import ch.zhaw.it.pm3.databaseHandling.DataManager;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.util.HashMap;

/**
 * Main class of the app
 */
public class App extends Application {
    private DataManager dataManager;
    private HashMap<String, Parent> screens = new HashMap<>();
    private static final String THEME = "views/css/ViewStyle.css";

    public static void main(String[] args) {
        launch(args);
    }

    /**
     * Initializes all screens and loads the start-view.
     * @param primaryStage to set the scene into
     * @throws Exception
     */
    @Override
    public void start(Stage primaryStage) throws Exception {
        loadAllScreens();
        startView(primaryStage);
    }

    /**
     * Saves all the data when the app stops.
     */
    @Override
    public void stop() {
        dataManager = DataManager.getInstance();
        dataManager.saveData();
    }

    private void startView(Stage stage) {
        try {
            Scene scene = new Scene(screens.get(Config.LOGIN));

            // configure and show stage
            stage.setScene(scene);
            stage.show();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadAllScreens() {
        loadScreen(Config.LOGIN, Config.LOGIN_FILE);
        loadScreen(Config.REGISTRATION, Config.REGISTRATION_FILE);
        loadScreen(Config.HOME, Config.HOME_FILE);
        loadScreen(Config.ADVERTISEMENT, Config.ADVERTISEMENT_FILE);
        loadScreen(Config.LIST_VIEW, Config.LIST_VIEW_FILE);
        loadScreen(Config.OFFER, Config.OFFER_FILE);
        loadScreen(Config.PROFILE, Config.PROFILE_FILE);
        loadScreen(Config.CONTRACT, Config.CONTRACT_FILE);

    }

    private void loadScreen(String name, String fileName) {
        try {
            FXMLLoader loader = new FXMLLoader(getClass().getResource(fileName));
            Parent loadScreen = loader.load();
            ControlledScreens controlledScreen = loader.getController();
            controlledScreen.setScreenList(screens);
            loadScreen.getStylesheets().add(THEME);
            screens.put(name, loadScreen);
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
            e.getMessage();
        }
    }
}
